name: Build wheels for aarm64

on:
  # [push, pull_request]
  workflow_dispatch:

env:
  CIBW_ARCHS_LINUX: "aarch64"
  CIBW_BUILD: "cp312-manylinux_aarch64 cp313-manylinux_aarch64"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]
        # os: [ubuntu-latest, ]
        # os: [ubuntu-latest, windows-latest, ]
        os: [ubuntu-24.04-arm, ]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3

      - name: Build wheels
        run: |
          cd pycrmod_v1/
          python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
        #   ...

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: pycrmod_v1/wheelhouse/*.whl
