name: Build wheels on Windows

on:
  # [push, pull_request]
  workflow_call:
  workflow_dispatch:

env:
  CIBW_ARCHS_WINDOWS: "AMD64"
  CIBW_BUILD: "cp312-win_* cp313-win_* "

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]
        # os: [ubuntu-latest, ]
        os: [windows-latest, ]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3 delvewheel

      - name: Build wheels
        run: |
          cd both_v1/
          python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
        #   ...
      - name: Fix wheels with delvewheel
        run: |
          cd both_v1/wheelhouse
          python -m delvewheel show *.whl
          python -m delvewheel repair -v *.whl

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          # note: this is the target directory for delvewheel
          path: both_v1/wheelhouse/wheelhouse/*.whl
