name: Build source distribution

on:
  # [push, pull_request]
  workflow_call:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          pip install build
      - run: |
          cd both_v1
          python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: pycrtomomod_sdist
          path: both_v1/dist/*.tar.gz
