name: V2 Trigger all wheel builds

on:
  workflow_dispatch:

jobs:
  build_aarch64:
    uses: ./.github/workflows/build_wheels_for_aarch64.yml
  build_amd64:
    uses: ./.github/workflows/build_wheels_for_amd64.yml
  build_armv7l:
    uses: ./.github/workflows/build_wheels_for_armv7l.yml
  build_windows:
    uses: ./.github/workflows/build_wheels_for_win.yml
